delete local and remote tracking branch feature added

diff --git a/gitty b/gitty
--- a/gitty
+++ b/gitty
@@ -1,9 +1,34 @@
 #!/bin/bash
+
+#
+# name of remote origin repository 
+#
+ORIGIN='origin';
+
+#
+#name of development branch that must be merged before pushing commiting other branches
+#
+DEVELOP='develop';
+
+#
+#count the number of args passed
+#
+ARGS=$#
+
+
+function CheckCheckoutError {
+	 #set -e will stop script if git throws an error
+	 set -e
+  	 git checkout "$1"
+  	 set +e
+}
+
+
 case "$1" in
 new-branch)
    	if [ "$2" != "" ] 
 	then
-		git checkout develop
+		CheckCheckoutError develop
 		git checkout -b "$2"
 		git push -u origin "$2"
 	else
@@ -14,7 +39,7 @@ retrieve-branch)
    	if [ "$2" != "" ] 
 	then
 		git fetch
-		git checkout develop
+		CheckCheckoutError develop
 		git merge origin/develop
 		git checkout --track -b $2 origin/$2
 	else
@@ -24,16 +49,14 @@ retrieve-branch)
 submit)
   if [ "$2" != "" ]; then
     if [ "$3" != "" ]; then
-      git checkout "$2"
+      CheckCheckoutError "$2"
       git commit -am "$3"
       #git add .
       git checkout develop
       git merge origin/develop
       git checkout "$2"
   	  OUTPUT=$(git merge develop)
-  	  echo "outputting:"
       echo $OUTPUT
-      echo "done outputting."
       if [[ "$OUTPUT" == *CONFLICT* ]]; then
         echo 'CONFLICT DETECTED - Running mergetool:'
       	git mergetool
@@ -47,19 +70,56 @@ submit)
     echo "please supply a branch name: gitty commit-push 'branch-name-to-commit-to' 'commit-message'"
   fi
 ;;
-#delete)
-#	if [ "$2" != "" ] 
-#	then
-#		git checkout develop
-#		git branch -d "$2"
-#		#read -p "remote branch $2 is not merged 'gooba gooba gooba' (y/n)?"
-#		#[ "$REPLY" == "y" ] || echo "gooba gooba gooba"
-#		git branch -d -r origin/"$2"
-#		
-#	else
-#		echo "please supply a branch name: gitty 'branch-to-delete-name'"
-#	fi
-#;;
+delete)
+	if [ "$2" != "" ] 
+	then
+		set -e
+		if [ "$ARGS" == "3" ]; then
+			if [[ "$3" == '-force' ]]; then
+				CheckCheckoutError $2
+				CheckCheckoutError $DEVELOP
+				echo "Forcing branch deletion of $2 and $ORIGIN/$2"
+				git branch -D $2
+				git branch -D -r $ORIGIN/$2
+			else
+				"echo Unknown option $2. did you mean '-force'?"
+				exit
+			fi
+			
+			echo ''
+			echo 'Force deletion successfully completed!'
+			
+		else
+			CheckCheckoutError $2
+			CheckCheckoutError $DEVELOP
+			
+			echo "Deleting $2"
+			set +e
+			OUTPUT=$(git branch -d "$2")
+			set -e
+			if [[ "$OUTPUT" == "" ]]; then
+				echo "'Not Fully Merged with $DEVELOP' error, you may use the '-force' option to force delete."
+				exit
+			fi
+			
+			echo "Deleting $2 and $ORIGIN/$2"
+			set +e
+			OUTPUT=$(git branch -d -r $ORIGIN/$2)
+			set -e
+			if [[ "$OUTPUT" == "" ]]; then
+				echo "'Not Fully Merged with $ORIGIN/$DEVELOP' error, you may use the '-force' option to force delete."
+				exit
+			fi
+			echo ''
+			echo 'Deletion successfully completed!'
+						
+		fi
+		set +e
+		
+	else
+		echo "please supply a branch name: gitty 'branch-to-delete-name'"
+	fi
+;;
 *)
   echo "pass in the following arguments:";
   echo " ";
@@ -71,7 +131,8 @@ submit)
   echo " ";
   echo "retrieve-branch 'remote-branch-name'"
   echo "Will create, checkout, track and pull a remote branch that does not yet exist locally"
-	#echo " ";
-      #echo "delete 'branch-name'"
-	#echo "will delete local and remote branch"
+  echo " ";
+  echo "delete 'branch-name' [-force]"
+  echo "will delete local and remote branch but will check if they are merged with other branches first for safety. Passing the optional -force parameter will force the deletion even if it is not merged in. "
 esac
+
